spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework_system?serverTimezone=GMT%2B8&useSSL=true
    username: root   #数据库
    password: toor #密码
  servlet:
    multipart:
      max-request-size: 5GB
      max-file-size: 1GB

